services:
  nginx:
    image: ${NGINX_IMAGE:?NGINX_IMAGE is required}
    build: null
    volumes:
      - nginx-certs:/etc/nginx/certs
      - certbot-www:/var/www/certbot
      - projects-storage:/var/projects

  backend:
    image: ${BACKEND_IMAGE:?BACKEND_IMAGE is required}
    build: null
    env_file:
      - ./.env.backend.local
    environment:
      AdminSecurity__Email: serbul11@mail.ru
      EmailVerification__Enabled: "true"
      EmailVerification__SmtpHost: smtp.mail.ru
      EmailVerification__SmtpPort: "587"
      EmailVerification__UseSsl: "true"
      EmailVerification__SmtpUser: serbul11@mail.ru
      EmailVerification__FromEmail: serbul11@mail.ru

  postgres:
    image: ${POSTGRES_IMAGE:?POSTGRES_IMAGE is required}
    build: null
